providers = ["node", "python"]

[phases.setup]
nixPkgs = ["pkgs.nodejs", "pkgs.npm", "pkgs.python311"]

[phases.install]
cmds = ["npm install", "pip install -r requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "bash start.sh"
